### ISSUE TITLE
Unnecessary preprocessing of geometries for Bokeh - Lesson 5

### ISSUE THREAD

**Issue by DmitriyLeybel** [Automating-GIS-processes/2017#1]
Bokeh can use the geometries of GeoDataFrames off the cuff if you first convert them to JSON, followed by creating a GeoJSONDataSource, and feeding it to it. 
e.g. GeoJSONDataSource(geojson=GeoDataFrame.to_json())

Then you use the GeoJSONDataSource as you would a ColumnDataSource, as Bokeh does the conversions internally. The conversion to x's and y's or xs' and ys' occurs, so you are able to use those as column names.

P.S. Very informative course. Thank you!

**Comment by HTenkanen** [comment]
@DmitriyLeybel Ah perfect! Thanks for sharing! 👍  Did not have time to check the latest changes on bokeh, hence, the materials were lacking behind a bit. A year ago this feature was not yet available (as far as I know). I will test and modify the materials accordingly. Thank you!

**Comment by HTenkanen** [comment]
@DmitriyLeybel Added a hint about the possibility to use a `GeoJSONDataSource` at the end of the following page: https://automating-gis-processes.github.io/2017/lessons/L5/advanced-bokeh.html 

Needed to keep this (i.e. parsing the xs and ys with dedicated functions) now like they were for consistency with the lecture videos but will update all materials for the next year.
